name: csslib
version: 0.17.3-dev
description: A library for parsing and analyzing CSS (Cascading Style Sheets)
repository: https://github.com/dart-lang/csslib

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  source_span: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  path: ^1.8.0
  term_glyph: ^1.2.0
  test: ^1.16.0
