name: csslib
version: 0.17.0-nullsafety.0

description: A library for parsing CSS.
homepage: https://github.com/dart-lang/csslib

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  source_span: ^1.8.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety.2
